### ISSUE TITLE
Compile Errors 

### ISSUE THREAD

**Issue by Nightfly1704** [brownrb/myFP2ESPFirmware#10]
I get Compile errors due to incorrect Typing
Firmware version 214 Compiled today

In myFP2ESP.ino 
Line 342 mySetupData->set_motorSpeed(SLOW); should be -> mySetupData->set_motorspeed(SLOW);
Line 345 mySetupData->set_motorSpeed(MED); should be -> mySetupData->set_motorspeed(MED);
Line 348 mySetupData->set_motorspeed(FAST); should be -> mySetupData->set_motorspeed(FAST);

Line 1253 #if (mycontrollermode == ACCESSPOINT) || (mycontrollermode == STATIONMODE) should be -> #if (CONTROLLERMODE == ACCESSPOINT) || (CONTROLLERMODE == STATIONMODE)

the TCP/IP Server isn't started automatic without this change an the IP Address listed on the OLED is 000.000.000.000

in temp.cpp
Line 16 #include <DallasTemperature.h> should be -> #include <myDallasTemperature.h>

in temp.h
Line 10 #include <DallasTemperature.h> should be -> #include <myDallasTemperature.h>

Great software thank You for your Work

**Comment by brownrb** [comment]
Many thanks
I have put this directly into "main" and made the release as "Release 214-1"
