### ISSUE TITLE
Pushbuttons don't work

### ISSUE THREAD

**Issue by Nightfly1704** [brownrb/myFP2ESPFirmware#16]
myFP2ESP.ino

Line 540 change from if ( (mySetupData->get_brdpb1pin() == 1) && (mySetupData->get_brdpb2pin() == 1) ) to
                                   if ( (mySetupData->get_brdpb1pin() != -1) && (mySetupData->get_brdpb2pin() != -1) )

Line 565 change from if ( (mySetupData->get_brdpb1pin() == 1) && (mySetupData->get_brdpb2pin() == 1) ) to 
                                  if ( (mySetupData->get_brdpb1pin() != -1) && (mySetupData->get_brdpb2pin() != -1) )

the call mySetupData->get_brdpb1pin() returns Pin Number not 0 or 1 so if Pin Numer is not equal -1 (not assigned) check Buttons

**Comment by brownrb** [comment]
Fix applied in 222-6
